library(igraph)
library(influenceR)
dat <- read.csv("Graph1/datasets/data-filtered.csv", header = TRUE)
mat <- as.matrix(dat)
g <- graph.data.frame(dat)

print(length(g))
print(ecount(g))

print("Średnica: ")
print(diameter(g))
print("Promień: ")
print(radius(g))
print("Gęstość: ")
print(graph.density(g))
